### ISSUE TITLE
Missing class when used with Spark 1.6 and Hadoop 2.6

### ISSUE THREAD

**Issue by gilv** [CODAIT/stocator#137]
We need to add maven profile for builds with Hadoop 2.6 and include guava-21.0.jar for those builds. 
Otherwise 

`Exception in thread "main" java.lang.NoClassDefFoundError: com.google.common.util.concurrent.ListeningExecutorService
        at java.lang.J9VMInternals.prepareClassImpl(Native Method)
        at java.lang.J9VMInternals.prepare(J9VMInternals.java:291)
        at java.lang.Class.getConstructor(Class.java:531)
        at com.ibm.stocator.fs.ObjectStoreVisitor.getStoreClient(ObjectStoreVisitor.java:114)
        at com.ibm.stocator.fs.ObjectStoreFileSystem.initialize(ObjectStoreFileSystem.java:94)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2596)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
`

Will be thrown.

@djalova Can you check it please?

**Comment by djalova** [comment]
@gilv Can you send me a pom file with those dependencies?

**Comment by gilv** [comment]
not sure we need this at this point. seems resolved
